# =======================================================================
# Copyright 2025 The SLiteIO Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# =======================================================================

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: obnvmf-disk-agent-thin-app
  namespace: obnvmf
spec:
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 200
    type: RollingUpdate
  selector:
    matchLabels:
      app: obnvmf-disk-agent-thin
  template:
    metadata:
      labels:
        app: obnvmf-disk-agent-thin
    spec:
      nodeSelector:
        lite.io/thin: 'true'
      #priorityClassName: system-node-critical
      serviceAccount: obnvmf-admin
      hostNetwork: true
      containers:
        - name: node-disk-agent-thin
          securityContext:
            privileged: true
            capabilities:
              add: ["ALL"]
            allowPrivilegeEscalation: true
          image: snleo123/node-disk-controller:v1.0
          #image: crpi-g408pn42wcgx8bkz.cn-hangzhou.personal.cr.aliyuncs.com/sliteio/node-disk-controller:v1.0  #国内镜像源
          #imagePullPolicy: Always
          command: ["sh", "-c", "ulimit -n 655350 && exec /node-disk-controller agent --nodeId=$(NODE_ID) --heartbeatInterval=20s --config=/config/agent-thin-config.yaml"]
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
            limits:
              cpu: "1"
              memory: "500Mi"
            requests:
              cpu: "100m"
              memory: "100Mi"
          volumeMounts:
            - name: device-dir
              mountPath: /dev
            # for File /usr/tmp/spdk.sock
            - name: spdk-sock-file-dir
              mountPath: /usr/tmp
            - name: agent-config
              mountPath: /config
            - name: data-dir
              mountPath: /local-storage
            - name: nvme-config
              mountPath: /etc/nvme
      volumes:
        - name: device-dir
          hostPath:
            path: /dev
            type: Directory
        - name: spdk-sock-file-dir
          hostPath:
            path: /var/spdk
            type: DirectoryOrCreate
        - name: data-dir
          hostPath:
            path: /local-storage
            type: DirectoryOrCreate
        - name: agent-config
          configMap:
            name: storage-setting
        - name: nvme-config
          hostPath:
            path: /etc/nvme
            type: DirectoryOrCreate
