# =======================================================================
# Copyright 2021 The LiteIO Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# =======================================================================
# Modifications by The SLiteIO Authors on 2025:
# - Modification : use new nvmf_tgt image to support lvm thin volume export and mount option:discard

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvmf-tgt
  namespace: obnvmf
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: nvmf-tgt
      role: node
  template:
    metadata:
      labels:
        app: nvmf-tgt
        role: node
    spec:
      serviceAccount: obnvmf-admin
      hostNetwork: true
      containers:
        - name: nvmf-tgt
          securityContext:
            privileged: true
            capabilities:
              add: ["ALL"]
            allowPrivilegeEscalation: true
          image: snleo123/nvmf_tgt:v1.6
          #image: crpi-g408pn42wcgx8bkz.cn-hangzhou.personal.cr.aliyuncs.com/sliteio/nvmf_tgt:v1.6  # 国内镜像源
          command:
          - nvmf_tgt
          args:
            - "-m"
            - "[1]"
            - "-s" #memory size in MB for DPDK
            - "256"
            - "--num-trace-entries"
            - "0"
          resources:
            requests:
              cpu: "1"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "512Mi"
              hugepages-2Mi: "512Mi"
          volumeMounts:
            - name: device-dir
              mountPath: /dev
            - name: log-dir
              mountPath: /tmp/log
            - name: hugepage
              mountPath: /hugepages
            - name: sock-dir
              mountPath: /usr/tmp
            - name: data-dir
              mountPath: /local-storage
      volumes:
        - name: device-dir
          hostPath:
            path: /dev
            type: Directory
        - name: log-dir
          hostPath:
            path: /tmp/log
            type: DirectoryOrCreate
        - name: sock-dir
          hostPath:
            path: /var/spdk
            type: DirectoryOrCreate
        - name: hugepage
          emptyDir:
            medium: HugePages
        - name: data-dir
          hostPath:
            path: /local-storage
            type: DirectoryOrCreate
