apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: obnvmf
spec:
  containers:
    - name: web
      image: nginx:latest
      resources:
        limits:
          cpu: "1"
          memory: 1Gi
        requests:
          cpu: "100m"
          memory: 100Mi
      volumeMounts:
        - name: data
          mountPath: /test-data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: pvc-obnvmf-test

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-obnvmf-test
  namespace: obnvmf
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: antstor-nvmf